### ISSUE TITLE
[Beta] Multi-cluster support

### ISSUE THREAD

**Issue by ostromart** [istio/enhancements#13]
# Beta Feature Requirements

This page lists the requirements for promoting multicluster to beta. Please check off and document the steps as they are completed.

### Requirements: 

**Features/Fixes**:
- ~~[ ] Istiod-less remote clusters (#27420) @linsun @stevenctl @irisdingbj~~ This didn't make 1.8 and will be addressed in a follow-on release.
- [x] Simplify multi-network onboarding @stevenctl 
  - [x] (Merged, istio/istio#25554) Implement Simplify Multi-network Configuration 
  - [x] (Merged, istio/istio#27049 ) Implement Decouple Cross-Network Gateways from Clusters
- [x] Support a custom gateway for east-west traffic (#27774) @stevenctl
- [x] Default network for cluster (#28126) @stevenctl 
- [x] Use remote profile (https://github.com/istio/istio.io/pull/8331) @nmittler. This allows us to automatically upgrade to remote clusters as features evolve.

**Tests**:

- [ ] Convert Telemetry E2E tests to be “multicluster-aware” @gargnupur
  - istio/istio#26888
- [ ] Convert Security E2E tests to be "multicluster-aware" 
  - istio/istio#25054
- [ ] Convert Networking E2E tests to be "multicluster-aware @stevenctl
  - istio/istio#24581

**Docs**:

Each task here also includes providing an automated test for the document on istio.io.

- [x] New multicluster install docs @nmittler 
- [x] Update plug-in CA docs @nmittler 
- [x] Update multicluster install docs for east-west gateway changes (https://github.com/istio/istio.io/issues/8303) @nmittler
- [x] Update multicluster install docs for new network config (https://github.com/istio/istio.io/issues/8304) @nmittler

**Approvals**

- [x] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [x] The [supportability review](https://docs.google.com/document/d/1-YRKf67ptsRov-s-Z2gJ4VaI-T9s6SPS_Nu_W-iJ0d8/edit#) panel has reviewed promotion of the feature. 
- [x] The TOC has reviewed and approved promotion of the feature as part of the
	road map for a release.

**Comment by nmittler** [comment]
Majority of the e2e tests have been migrated. We've raised a few issues to finish off the remaining tests, but the work in 1.8 is sufficient for beta. Closing this and will finish the remaining work in a patch release.
