### ISSUE TITLE
[Experimental] Publishing multi-arch images to support non-amd64 cluster

### ISSUE THREAD

**Issue by morlay** [istio/enhancements#14]
[//]: # (The syntax preceeding this line is a comment marker used to help guide the issue author with submission of an issue)
[//]: # (to github. Unlike HTML comments commonly used throughout istio.io documentation, this comment will not be rendered)
[//]: # (by github. Comments must be separated by carriage return preceding and concluding the text and be a single line.)

[//]: # (This page lists the requirements for an experimental feature. Completion of this template enables Istio work groups)
[//]: # (to collect information on potential new functionality. This template should be completed before users are exposed to)
[//]: # (any new experimental feature. Please complete this template during development.)

[//]: # (The feature implementation section must be completed before submission of the issue.)

# Feature:

**Feature name:**

Publishing multi-arch images of `isitio/operator` `isitio/proxyv2`  `isitio/pilot`  to support non-amd64 cluster

**Primary lead(s):**

**Short description:**

With multi-arch image, final user could be install istio in non-amd64 cluster, without change any configuration. 

# Requirements:

[//]: # (All information in this section is mandatory for promotion. Please edit the issue to modify the links in this)
[//]: # (section.)

- [x] multi-arch images for `istio/base` `istio/distroless` `istio/iptables` (upstreams ready, waiting for releasing)
- [ ] multi-arch istio envoy binary (https://github.com/istio/enhancements/issues/14#issuecomment-740328750)
- [ ] multi-arch go binaries (https://github.com/istio/enhancements/issues/14#issuecomment-740333103)
- [ ] multi-arch image (https://github.com/istio/enhancements/issues/14#issuecomment-740338088)

- [ ] [User stories](insert_your_link_here) reviewed in a work group meeting.

[//]: # (User stories are a way to communicate user value. User stories follow the style)
[//]: # (as a [type of user], I want [an action] so that [a benefit/a value]. Istio currently has no user)
[//]: # (story template. Maybe you can make one?)

[//]: # (User stories must be presented in a work group meeting. They need no approval and are later integrated)
[//]: # (into the RFCs, which do need approval for alpha. You may find value to negotiate within the work group where the)
[//]: # (user stories are presented to help clarify the user stories.)

- [ ] [RFC Authored] - [create an RFC using template](https://docs.google.com/document/d/1ewJoCcw5-04crH-M0xw4zFxz1cfwVCPnNyW4K3m4Yyc/template/preview).

[//]: # (An RFC is mandatory to graduate to experimental. The RFC does not have to be reviewed in a work group)
[//]: # (meeting to graduate to experimental.)

- [ ] [Documentation](insert_your_link_here) for enabling and using the feature.

[//]: # (The documentation instructions may exist on the developer wiki or the team drive. They may include instructions)
[//]: # (for building running a `istioctl experimental command`, or using the preview profile,)
[//]: # (or any other relevant information.)

- [ ] [Feedback plan](insert_your_link_here).

[//]: # (This may include user feedback meetings, discuss.istio.io conversations, GitHub issues, or mailing lists.)

- [ ] Disabled by default.

- [ ] No impact on performance when the feature is disabled.

**Comment by morlay** [comment]
# multi-arch istio envoy binary

I try to upgrade build-env to multi-arch build https://github.com/istio/tools/pull/1346.
but failed. 
we seems not setup envoy-build-env for arm64.

considering upgrade to the `ubuntu:18.04` (as enovyproxy/envoy did), and make envoy-build-env simple.  
https://github.com/querycap/istio/blob/master/build/istio-envoy-build-env/Dockerfile.istio-envoy-build-env

for final enovy builds, need pure arm64 host (8u+). qemu will very very slow.

**Comment by morlay** [comment]
# multi-arch go binaries

istio outputs need to upgrade. arch may be as suffix

```
out/linux/
   operator-amd64
   operator-arm64
```

**Comment by morlay** [comment]
# multi-arch image

when multi-arch go binaries and multi-arch envoy ready, 

we could easy build multi-arch image with `docker buildx build --platform=linux/amd64,linux/arm64`, but with some changes for Dockerfiles like

```Dockerfile
ARG TARGETARCH
COPY operator-${TARGETARCH} /operator
```

**Comment by sdake** [comment]
@morlay are you the primary lead for this feature, or do you have coleads?

Cheers,
-steve

**Comment by morlay** [comment]
@sdake 

not understand the primary lead means.

i already build multi arch images in https://github.com/querycap/istio by myself
And tested on my arm64 cluster

But, for merging my works to isito, something i could not make a decision.  So i don't think i could be lead for the feature

**Comment by brian-avery** [comment]
Migrated to https://github.com/brian-avery/enhancements/blob/migrateFeaturesToFiles/features/multi-arch_images.md as part of #26
