### ISSUE TITLE
Telemetry API Graduation to Stable

### ISSUE THREAD

**Issue by whitneygriffith** [istio/enhancements#155]
RFC: [Drive Telemetry API Existing Fields to Beta](https://docs.google.com/document/d/16A-E-30txN5Y2V_9qrDNpVC3lT7P6aa_3Qdg6_4t5Sg/edit) 
[api/3133](https://github.com/istio/api/pull/3133)

### Background:

Users are requesting increased stability for the Telemetry API so that they can solely use the API to configure Telemetry options

### Feature/Process Owner:
Whitney Griffith 

### Subtasks:
- [x] Feature owner is gathering consensus on scope
- [x] Defining the subgroup’s objective for this feature graduation
- [x] Resolve scope by end of September 27th 
- [x] Create Specific tasks by Oct 9th. At this point we freeze the things to do. 
- [ ] #159 
- [ ] Update Enhancements Feature Checklists

**Comment by whitneygriffith** [comment]
[#3133](https://github.com/istio/api/pull/3133)
