### ISSUE TITLE
[stable] multi-cluster support

### ISSUE THREAD

**Issue by stevenctl** [istio/enhancements#38]
beta issue: https://github.com/istio/enhancements/issues/13

This document covers the stability of multi-primary and primary-remote configurations.

This does _not_ include:
* external control plane
* multi-network

# Stable Feature Requirements

This page lists the requirements for promoting multicluster to **stable**. Please check off and document the steps as they are completed.

### Requirements

**Features/Fixes:**
* [x] https://github.com/istio/istio/issues/32364
* [x] headless services (https://github.com/istio/istio/issues/27342, https://github.com/istio/istio/issues/29969)
* [x] https://github.com/istio/istio/issues/31787
* [x] https://github.com/istio/istio/issues/29335
* [x] https://github.com/istio/istio/issues/31464
* [x] https://github.com/istio/istio/issues/28906
* [x] https://github.com/istio/istio/issues/30625
* [x] https://github.com/istio/istio/issues/29900
* [x] https://github.com/istio/istio/issues/29482
* [x] https://github.com/istio/istio/issues/27420
  * [X] Re-enable tests (temporarily in a separate prow job(s) using [test framework settting](https://github.com/istio/istio/blob/master/pkg/test/framework/components/istio/flags.go#L53)
  * [] A workaround for our test infra that avoids patching ISTIOD_CUSTOM_HOST (to closer match what we document for users).
  * https://github.com/istio/istio/issues/33619
  * [ ] Document installation steps.  (https://github.com/istio/istio.io/issues/9618)
* [ ] bug-report support https://github.com/istio/istio/issues/32321

**Tests:**

* [x] multicluster networking ingress coverage (https://github.com/istio/istio/issues/32282)
* [ ] ~Draining traffic to a cluster and removing it from a mesh~
* [ ] security test flakes (https://github.com/istio/istio/issues/32172)
* [ ] security test gaps (https://github.com/istio/istio/issues/32287)
* [ ] test failures: `corsPolity` breaks using VM + Multi-Cluster (https://github.com/istio/istio/issues/31532)
* [ ] gRPC in security tests (https://github.com/istio/istio/issues/32280)
* [ ] enhance mirroring test checks (https://github.com/istio/istio/issues/32284)

 **Docs:**

Each task here also includes providing an automated test for the document on istio.io.

* [ ] headless/statefulsets - https://github.com/istio/istio.io/issues/8832
* [ ] https://github.com/istio/istio.io/issues/8605
* [ ] https://github.com/istio/istio.io/issues/8603
* [ ] https://github.com/istio/istio.io/issues/8469
* [ ] https://github.com/istio/istio.io/issues/9559
* [x] https://github.com/istio/istio.io/issues/9558
* [ ] instructions for revisioned upgrade of east-west gateway (https://github.com/istio/istio/issues/30526)

**Other:**
* [ ] Revisit the [supportability review](https://docs.google.com/document/d/1-YRKf67ptsRov-s-Z2gJ4VaI-T9s6SPS_Nu_W-iJ0d8/edit#heading=h.1ea3ns3s6e6c) for beta

**Approvals:**
- [ ] The appropriate work group(s) have reviewed and approved promotion of the feature.
- [ ] The supportability review panel has reviewed promotion of the feature.
- [ ] The TOC has reviewed and approved promotion of the feature as part of the
	road map for a release.

**Comment by hzxuzhonghu** [comment]
We also need cluster-aware load balancing when clusters are in different networks

**Comment by stevenctl** [comment]
Multi-network is a separate concern from multi-cluster

**Comment by brian-avery** [comment]
@stevenctl can you please create a PR for this following https://github.com/istio/enhancements/blob/master/FEATURES.md? Thanks

**Comment by stevenctl** [comment]
@brian-avery  I started moving it over... but I'll do that as the last step. That format is pretty hard to use as a living checklist while the work is in progress.

**Comment by eduardobaitello** [comment]
Does this issue still make sense? It's no longer being updated, especially regarding ambient Mesh.
